version: '3'
services:
  service:
    image: service
    build: service/
    environment:
      - PUBLIC_DIR=upload/files
      - FILENAME_SIZE=10
      - DB_HOST=db
      - DB_NAME=files
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8080
    volumes:
      - ./upload/files:/app/upload/files
    ports:
      - 8080:8080  

  db:
    image: postgres
    restart: always
    container_name: marketplace-postgress
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=files
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 2s
      retries: 5
      start_period: 2s
      timeout: 10s